  
alias ze="zellij attach -c -f main "
alias zec="zellij attach -c -f "
alias zetmp="zellij attach -c -f tmp options --default-layout compact"
alias zedefault="zellij -l default"
alias zecompact="zellij -l compact"
alias zeclassic="zellij -l classic"
zeclear() {
    zellij ls \
        | sed -E 's/\x1B\[[0-9;]*[[:alpha:]]//g' \
        | awk '/EXITED/ {print $1}' \
        | xargs -r -I {} zellij delete-session "{}"
}
